package helloworld;

/**
 *
 * @author javie
 */

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class LoginGUI extends JFrame {
    private JFrame frame;
    private JTextField txtUsername;
    private JPasswordField passwordField;
    
//    public static void main(String[] args) {
//        // TODO code application logic here
//        LoginGUI lg = new LoginGUI();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Constructor
    public LoginGUI() {
        displayLoginGUI();
    }

    /**
     * Initialize the contents of the frame.
     */
    public void displayLoginGUI() {
        frame = new JFrame("Login");
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setBounds(100, 100, 600, 500);
        frame.getContentPane().setLayout(null);
        
        JLabel lblTitle = new JLabel("HelloWorld");
        lblTitle.setFont(new Font("Tahoma", Font.BOLD, 28));
        lblTitle.setBounds(230, 140, 200, 31);
        frame.getContentPane().add(lblTitle);
        
        JLabel lblSubtitle = new JLabel("A research conference management system software.");
        lblSubtitle.setFont(new Font("Tahoma", Font.PLAIN, 15));
        lblSubtitle.setBounds(130, 165, 400, 31);
        frame.getContentPane().add(lblSubtitle);

        JLabel lblUsername = new JLabel("Username : ");
        lblUsername.setBounds(200, 204, 80, 31);
        lblUsername.setFont(new Font("Tahoma", Font.PLAIN, 14));
        frame.getContentPane().add(lblUsername);

        JLabel lblPassword = new JLabel("Password : ");
        lblPassword.setFont(new Font("Tahoma", Font.PLAIN, 14));
        lblPassword.setBounds(200, 245, 80, 31);
        frame.getContentPane().add(lblPassword);

        txtUsername = new JTextField();
        txtUsername.setBounds(275, 211, 131, 20);
        frame.getContentPane().add(txtUsername);
        txtUsername.setColumns(10);

        passwordField = new JPasswordField();
        passwordField.setBounds(275, 252, 131, 20);
        frame.getContentPane().add(passwordField);

        JButton btnLogin = new JButton("Login");
        btnLogin.setBounds(230, 290, 150, 31);
        frame.getContentPane().add(btnLogin);

        frame.setVisible(true);

        btnLogin.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent e) 
            {
                String username = txtUsername.getText();
                String password = String.valueOf(passwordField.getPassword());

                LoginController lc = new LoginController();
                boolean result = lc.login(username, password);
                if(result){
                    String profile = lc.checkProfile(username);
                    switch(profile.toLowerCase()){
                        case "system admin":
                            createSystemAdminGUI();
                            break;
                        case "author":
                            createAuthorGUI();
                            break;
                        case "reviewer":
                            createReviewerGUI();
                            break;
                        case "conference chair":
                            createConferenceChairGUI();
                            break;
                        default:
                            break;
                    }
                    frame.dispose();
                } else{ 
                    JOptionPane.showMessageDialog(btnLogin, "The username or password you entered is incorrect.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });		
    }
    
    public void createSystemAdminGUI(){
        new SystemAdminGUI();
    }
    
    public void createAuthorGUI(){
        new AuthorGUI();
    }
    
    public void createReviewerGUI(){
        new ReviewerGUI();
    }
    
    public void createConferenceChairGUI(){
        new ConferenceChairGUI();
    }
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
